// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package takeaway

import (
	"gf-demo-takeaway/api/takeaway"
)

type ControllerV1 struct{}

func NewV1() takeaway.ITakeawayV1 {
	return &ControllerV1{}
}
