// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package takeaway

import (
	"gf-demo-takeaway/api/takeaway"
)

type ControllerV2 struct{}

func NewV2() takeaway.ITakeawayV2 {
	return &ControllerV2{}
}
