// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-demo-takeaway/internal/dao/internal"
)

// internalAuthcodeDao is internal type for wrapping internal DAO implements.
type internalAuthcodeDao = *internal.AuthcodeDao

// authcodeDao is the data access object for table authcode.
// You can define custom methods on it to extend its functionality as you wish.
type authcodeDao struct {
	internalAuthcodeDao
}

var (
	// Authcode is globally public accessible object for table authcode operations.
	Authcode = authcodeDao{
		internal.NewAuthcodeDao(),
	}
)

// Fill with you ideas below.
